### ISSUE TITLE
Missing Dataset 

### ISSUE THREAD

**Issue by hongwang01** [longbai1006/LLCaps#4]
Thanks for the interesting work. Could you please provide the complete data set, including the external validation set with 100 images from KC and the images with mask annotations for the downstream RLE segmentation, as listed in Table 1? Thanks.

**Comment by longbai-cuhk** [comment]
Hi! Thank you for your interest. The mentioned data have been updated in the README.

**Comment by hongwang01** [comment]
> Hi! Thank you for your interest. The mentioned data have been updated in the README.

 Sincerely thanks
